# locations and things
OPERATOR_SDK_DIR=$HOME/operator-sdk
OPERATOR_SDK_CMD=operator-sdk
OPERATOR_SDK_PATH=$OPERATOR_SDK_DIR/$OPERATOR_SDK_CMD
BUNDLES_PREFIX=bundle-
OPERATOR_BUNDLE_OCIR_REGION=iad.ocir.io
OSOK_BUNDLE_VERSION=1.1.1