---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: fluentd-to-es
  namespace: logging

---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: fluentd-to-es
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - namespaces
  verbs:
  - get
  - list
  - watch

---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: fluentd-to-es
roleRef:
  kind: ClusterRole
  name: fluentd-to-es
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: fluentd-to-es
  namespace: logging
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: fluentd-to-es
  namespace: logging
  labels:
    k8s-app: fluentd-to-es
    version: v1
spec:
  selector:
    matchLabels:
      k8s-app: fluentd-to-es
      version: v1
  template:
    metadata:
      labels:
        k8s-app: fluentd-to-es
        version: v1
    spec:
      serviceAccount: fluentd-to-es
      serviceAccountName: fluentd-to-es
      tolerations:
      - key: node-role.kubernetes.io/master
        effect: NoSchedule
      containers:
      - name: fluentd-to-es
        image: fluent/fluentd-kubernetes-daemonset:v1-debian-elasticsearch
        env:
          - name:  FLUENT_ELASTICSEARCH_HOST
            value: "elasticsearch-master.logging.svc"
          - name:  FLUENT_ELASTICSEARCH_PORT
            value: "9200"
          - name: FLUENT_ELASTICSEARCH_SCHEME
            value: "http"
          # Option to configure elasticsearch plugin with self signed certs
          # ================================================================
          - name: FLUENT_ELASTICSEARCH_SSL_VERIFY
            value: "true"
          # Option to configure elasticsearch plugin with tls
          # ================================================================
          - name: FLUENT_ELASTICSEARCH_SSL_VERSION
            value: "TLSv1_2"
          # X-Pack Authentication
          # =====================
          - name: FLUENT_ELASTICSEARCH_USER
            value: "elastic"
          - name: FLUENT_ELASTICSEARCH_PASSWORD
            value: "changeme"
          # a parser type of cri is required for systems not using docker (Kuernetes 1.20 and later)
          # If you are using docker then you should use a type of json
          - name: FLUENT_CONTAINER_TAIL_PARSER_TYPE
            value: "cri"
          # The default format puts the time zone as a string (e.g. CET) however the output format includes it as an offset (+01:00)
          # So we need to override that and teplace the usual formatting of ∞Ω with %:z
          - name: FLUENT_CONTAINER_TAIL_PARSER_TIME_FORMAT
            value: "%Y-%m-%dT%H:%M:%S.%N%:z"
          # Ignore the fluentd logs - otherwise you can get some serious log type recursion going on
          - name: FLUENT_CONTAINER_TAIL_EXCLUDE_PATH
            value: "[\"/var/log/containers/fluentd*.log\"]"
          # Dont need to have fluentd looking for it's own systemd logs
          - name: FLUENTD_SYSTEMD_CONF
            value: "disable"
        resources:
          limits:
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 200Mi
        volumeMounts:
        - name: varlog
          mountPath: /var/log
        - name: varlibdockercontainers
          mountPath: /var/lib/docker/containers
          readOnly: true
        # The entries in /var/log/containers map into /u01/data/docker/containers in OKE
        - name: u01data
          mountPath: /u01/data/docker/containers/
      terminationGracePeriodSeconds: 30
      volumes:
      - name: varlog
        hostPath:
          path: /var/log
      # Where u01data goes       
      - name: u01data
        hostPath:
          path: /u01/data/docker/containers/
      - name: varlibdockercontainers
        hostPath:
          path: /var/lib/docker/containers
