apiVersion: v1
kind: Secret
metadata:
  name: stockmanagerdb
type: Opaque
stringData:
  dataSourceClassName: oracle.jdbc.pool.OracleDataSource
  url: jdbc:oracle:thin:@<database connection name>?TNS_ADMIN=./Wallet_ATP
  username: HelidonLabs
  password: H3lid0n_Labs
  hibernatedialect: org.hibernate.dialect.OracleDialect
  hibernateauto: update
  