apiVersion: split.smi-spec.io/v1alpha1
kind: TrafficSplit
metadata:
  name: stockmanager-canary
spec:
  service: stockmanager
  backends:
  - service: stockmanagerv0-0-1
    weight: 90
  - service: stockmanagerv0-0-2
    weight: 0