kind: IngressGateway
apiVersion: servicemesh.oci.oracle.com/v1beta1
metadata:
  name: store-ingress-gateway
spec:
  compartmentId: COMPARTMENT_OCID
  mesh:
    ref:
      name: store
  hosts:
    - name: storeHost
      hostnames:
        - store.example.com
      listeners:
        - port: 80
          protocol: TCP
          tls:
            mode: DISABLED
  accessLogging:
    isEnabled: true
